oissdluto: vermelho
uesuqe: vermelho
irquelite: vermelho
mecinostomo: vermelho
ectopargo: amarelo
ectopago: verde
liavel: verde
pichilijga: amarelo
endofrgmal: amarelo
jmegicera: vermelho
floroglucinocarbonico: verde
uiquelire: vermelho
udita: vermelho
iiipoca: vermelho
famiraprxnio: amarelo
lforicunlo: vermelho
teroroso: amarelo
faamiraprinio: amarelo
funereo: vermelho
nebris: verde
