procelerina: amarelo
op: vermelho
pgroacelerina: amarelo
npalmeapr: vermelho
natitnguiense: amarelo
azeitonxs: amarelo
xamate: vermelho
pilantna: amarelo
cafajestismo: vermelho
druiismo: amarelo
uacuiranga: vermelho
rajaxora: vermelho
glotogfonia: amarelo
eabslio: vermelho
treptodonte: verde
sectura: vermelho
ohmogonico: vermelho
snqilia: vermelho
eptosquema: amarelo
ihdropapaverina: vermelho
lisogeniyo: amarelo
puxinanaense: verde
enclhtismo: amarelo
cefalomedial: vermelho
potohino: amarelo
acastrelieo: vermelho
estremadurar: verde
potifar: vermelho
edccciiu: vermelho
fitologico: verde
contraruptura: amarelo
pichurins: verde
estnsremadurar: vermelho
guadalnuupe: vermelho
miristicacao: verde
ortiga: verde
pxinanaense: amarelo
crioogia: amarelo
osmadizona: verde
mnguza: amarelo
prastrano: verde
aspasiense: vermelho
closiramina: vermelho
talmanca: amarelo
barbaramente: verde
prcelerina: vermelho
inquilia: amarelo
apovelosoal: amarelo
eilionarizantm: vermelho
exempla: amarelo
zimosimezrico: amarelo
behmudo: amarelo
homogonico: verde
charoles: vermelho
milioznarijzante: vermelho
xocipo: vermelho
natinguiee: vermelho
justapocsicao: amarelo
esfenofilostaquide: verde
prosteieo: vermelho
pacastrelineo: verde
tilanpra: vermelho
halocaris: verde
fotodixssociar: amarelo
leptosqucma: amarelo
manguiza: amarelo
castear: vermelho
glotogonfa: amarelo
tresiwela: amarelo
potosin: amarelo
bclusao: amarelo
epxemplar: amarelo
tritanari: vermelho
tamwbqui: vermelho
atelostoula: vermelho
ortiba: amarelo
ztrelear: amarelo
milionarizante: verde
guadfalupe: amarelo
osladizona: amarelo
araruama: verde
baplacao: vermelho
tiacetarsamida: vermelho
treptodondte: amarelo
druidismo: verde
eptosuema: vermelho
semanalistico: verde
crjruama: vermelho
barrtotar: amarelo
ohalocaris: amarelo
takjaniense: vermelho
panduro: verde
suriclona: verde
prqsjrano: vermelho
justaposrnicao: vermelho
atlide: amarelo
gloral: amarelo
esmelorar: amarelo
paciear: vermelho
semicartuttnesco: vermelho
