digyitaloina: vermelho
exaustos: verde
entopogao: verde
leucometrico: verde
secundanista: vermelho
gasqtroisterectdomia: vermelho
maua: vermelho
moeestrativo: vermelho
detilozoide: amarelo
huminifta: amarelo
rpflencia: vermelho
lucometrico: amarelo
esmintio: vermelho
tai: verde
erbiho: amarelo
sinfjilia: amarelo
ortognaissoso: verde
binfiliu: vermelho
tbmef: vermelho
poulencia: vermelho
homoaxial: verde
mawriolar: amarelo
crisorna: amarelo
gstroisterectomia: amarelo
rarmajudd: vermelho
sinflia: amarelo
antagonqistografo: amarelo
badominovaginal: vermelho
politraumatisbmo: amarelo
biplacenta: amarelo
ocordacaa: vermelho
tadilozoide: vermelho
miheiao: vermelho
ureteropielite: vermelho
hidrodessulfurizacao: vermelho
obednentemente: amarelo
sereno: vermelho
orobito: vermelho
frangao: verde
giebsonimta: vermelho
miospasico: verde
obedintemente: amarelo
exasos: vermelho
crhisorizna: vermelho
granulando: vermelho
anantivo: amarelo
antiprosaistico: verde
cebruno: vermelho
blivenite: amarelo
obm: vermelho
adojunar: vermelho
tgai: amarelo
aibsonitg: vermelho
icapirira: vermelho
extorjk: vermelho
oplivenite: amarelo
oivenite: amarelo
iniciativo: vermelho
metacarpiano: verde
metafarpiano: amarelo
