21 a distancia 0: acesa
2 a distancia 1: queimada
22 a distancia 1: acesa
23 a distancia 1: acesa
0 a distancia 2: queimada
1 a distancia 2: queimada
4 a distancia 2: queimada
3 a distancia 3: queimada
6 a distancia 3: queimada
14 a distancia 3: queimada
5 a distancia 4: queimada
7 a distancia 4: queimada
12 a distancia 4: queimada
13 a distancia 4: queimada
15 a distancia 4: queimada
16 a distancia 5: queimada
17 a distancia 5: queimada
18 a distancia 5: queimada
19 a distancia 5: queimada
20 a distancia 5: queimada
