c inserido em 0
g inserido em 0
t inserido em 0
g inserido em 3
c inserido em 4
c inserido em 3
t inserido em 4
g inserido em 7
a inserido em 1
c inserido em 5
a inserido em 9
g inserido em 10
c inserido em 5
g inserido em 11
a inserido em 13
t inserido em 7
t inserido em 3
a inserido em 9
g inserido em 1
a inserido em 12
a inserido em 10
t inserido em 8
t inserido em 1
g inserido em 14
g inserido em 18
c inserido em 24
a inserido em 0
t inserido em 21
g inserido em 7
g inserido em 29
c inserido em 24
a inserido em 5
c inserido em 27
t inserido em 25
a inserido em 24
t inserido em 3
c inserido em 19
subsequencia t g a a g t g c c c t c t a a g c t a g g c t a a t c g c g >> 1
g inserido em 11
g inserido em 33
g inserido em 0
a inserido em 9
c inserido em 33
c inserido em 36
a inserido em 5
c inserido em 9
t inserido em 32
g inserido em 16
c inserido em 46
a inserido em 42
g inserido em 41
g inserido em 19
t inserido em 42
t inserido em 11
g inserido em 40
c inserido em 44
a inserido em 19
t inserido em 40
c inserido em 19
g inserido em 24
t inserido em 0
g inserido em 0
a inserido em 50
g inserido em 5
t inserido em 9
g inserido em 41
c inserido em 35
a inserido em 39
g inserido em 1
g inserido em 16
t inserido em 32
a inserido em 21
t inserido em 53
g inserido em 1
t removido de 6
c inserido em 30
g inserido em 1
g inserido em 45
g inserido em 53
a inserido em 64
g inserido em 31
t inserido em 23
g inserido em 27
c inserido em 61
a inserido em 20
t inserido em 38
g inserido em 0
g inserido em 61
t inserido em 56
t inserido em 4
t inserido em 44
a inserido em 1
c inserido em 78
c inserido em 42
a inserido em 30
c inserido em 47
g inserido em 92
a inserido em 60
g inserido em 83
a inserido em 52
t inserido em 16
t inserido em 79
g inserido em 62
c inserido em 59
g inserido em 87
a inserido em 74
c inserido em 53
a inserido em 29
c inserido em 82
g inserido em 62
c inserido em 56
sequencia g a g g g t g t g a g t a a t t t g a c a g t a a g t a t a g g a g g c c a c g g c c g t c t t c c t t a a c a c g c c t a c g g a g g a g c t g t t g a g a a t t c t c c g t c g c a a g c g c t g g a c g c g c g g
a inserido em 95
g inserido em 85
g inserido em 38
c inserido em 47
c inserido em 12
g inserido em 1
t inserido em 114
t inserido em 2
g inserido em 70
c inserido em 19
g inserido em 29
t inserido em 109
a inserido em 75
t inserido em 14
t inserido em 92
g inserido em 77
c inserido em 1
t inserido em 93
t inserido em 78
a inserido em 21
c inserido em 31
g inserido em 123
g inserido em 89
a inserido em 28
c inserido em 132
g inserido em 64
t inserido em 85
g inserido em 42
a inserido em 25
c inserido em 70
c inserido em 100
a inserido em 117
c inserido em 22
a inserido em 126
t inserido em 14
a inserido em 11
c removido de 54
a inserido em 140
g inserido em 56
a inserido em 68
g inserido em 114
t inserido em 141
g inserido em 13
t inserido em 51
a inserido em 7
t inserido em 53
g inserido em 60
c inserido em 4
t inserido em 47
g inserido em 107
t inserido em 6
a inserido em 33
c inserido em 69
g inserido em 85
t inserido em 49
t inserido em 123
a inserido em 135
t inserido em 89
a inserido em 161
a inserido em 80
t inserido em 161
g inserido em 5
c inserido em 141
c inserido em 88
t inserido em 46
c inserido em 22
g inserido em 42
g inserido em 80
c inserido em 119
a inserido em 167
c inserido em 161
a inserido em 146
c inserido em 95
subsequencia c c a g g g g g c c g c t c c t t g c c t a a t g a a c c c g a c c t g c c t a c g g g a g a t g g t a g c t g t c g g t g a g c a a t t t t t c t c g g c g t c << 22
c inserido em 58
g inserido em 7
t inserido em 90
t inserido em 175
a inserido em 78
c inserido em 33
a inserido em 37
a inserido em 155
t inserido em 168
c inserido em 76
c inserido em 174
g inserido em 46
a inserido em 190
g inserido em 5
g inserido em 103
c inserido em 33
g inserido em 144
g inserido em 159
g inserido em 95
a inserido em 48
t inserido em 55
g inserido em 148
t inserido em 181
a inserido em 32
t inserido em 23
c inserido em 27
t inserido em 96
g inserido em 180
c inserido em 83
g inserido em 127
t inserido em 34
g inserido em 173
g inserido em 207
t inserido em 147
c inserido em 66
t inserido em 74
sequencia g c g t c g g a g t g g a g t g t a g g a g t t t c t c c a a t t a t a c c c c t g a a a a c a a g c c a g a g g g g t g c c g c t c c c t t c g c t c t a a t g a a c c c c g c a c c t a g c c t a c t g g g a g g a t t g g t a g g c t g t c g g t g a g c a a g t t t t t c t c g g c g t c t g a c t a g g t t a t g g a t t g g g a g g t t g a c g a a g a c a a g c a g c a g t g t t g t a c c c g g c g t a c t g t a a g g t a c
c inserido em 209
t inserido em 33
c inserido em 74
a inserido em 155
t inserido em 215
g inserido em 38
a inserido em 134
t inserido em 125
g inserido em 57
t inserido em 134
t inserido em 213
c inserido em 199
g inserido em 22
a inserido em 27
a inserido em 62
t inserido em 196
t inserido em 122
g inserido em 65
g inserido em 219
g inserido em 151
a inserido em 181
c inserido em 27
a inserido em 107
a inserido em 27
t inserido em 102
a inserido em 114
c inserido em 76
a inserido em 145
a inserido em 110
t inserido em 186
a inserido em 165
c inserido em 10
c inserido em 8
c inserido em 146
g inserido em 208
g inserido em 89
prefixo g c g t c g g a c g t c g g a g t g t a g g a g g t t t c a c a t c c a a t t t a t a c g c c c t g a a a a -> a a a a g t c c c g c a t a t t t a a c c t a c a c t t t g g a g g a t g t g a g g c t g c a g g c t g c g
c inserido em 10
a inserido em 141
a inserido em 237
t inserido em 125
g inserido em 78
g inserido em 154
t inserido em 32
g inserido em 217
a inserido em 138
c inserido em 34
t inserido em 80
a inserido em 158
a inserido em 116
c inserido em 66
a inserido em 193
a inserido em 167
c inserido em 156
t inserido em 103
c inserido em 79
c inserido em 1
g inserido em 110
g inserido em 199
t inserido em 31
c inserido em 221
c inserido em 51
c inserido em 257
g inserido em 99
t inserido em 66
g inserido em 36
t inserido em 181
a inserido em 279
a inserido em 221
t inserido em 109
a inserido em 176
g inserido em 89
g inserido em 97
prefixo a c a a a g t c c c g c c a t a t t t a a c c t a c a c t t t t g g t a g c g g a t g t g a g g c t g c c a g g c t g c g c a a g c c t a g a c g g g a g g -> g g a g g g c a g a t c c g a a c g c g t c g g a c c g t c g g a g t g t a g g c g a t g g t t t t c a c a t c c a a t t t a t a c c g c c c t g a a a c a
c inserido em 40
t inserido em 61
c inserido em 46
a inserido em 252
a inserido em 145
c inserido em 165
g inserido em 175
a inserido em 45
g inserido em 139
t inserido em 153
g inserido em 108
g inserido em 181
a inserido em 84
g inserido em 78
g inserido em 283
t inserido em 205
a inserido em 257
a inserido em 34
t inserido em 163
t inserido em 193
t inserido em 216
c inserido em 216
g inserido em 299
t inserido em 14
g inserido em 197
c inserido em 35
a inserido em 242
a inserido em 1
g inserido em 57
c inserido em 31
g inserido em 124
a inserido em 63
t inserido em 125
a inserido em 52
c inserido em 255
g inserido em 67
prefixo g a g a g g g c a g a t c c g t a a c g c g t c g g a c c g t c c g g a g c a t g t a g g c c g a t a g a c g t t t t g c a c a a t c g c a a t t t t a t a c c g c c c t g a g a a c a g t a g c c g c c t t g g c c c c t t c g g c c t c g g g t a a t -> t a a t g g g c t c c g g c t t c c c c g g t t c c g c c g a t g a c a a g a g t c c c g c c a t a t t t t a a c g c t a a c a c g t t t t g c a g a t a g c c g g a t g t a c g a g g c c t g c c a g g c t g c g c a a t g c c t a g a c g g g a g a g
c inserido em 316
c inserido em 294
c inserido em 249
c inserido em 215
c inserido em 72
g inserido em 299
c inserido em 92
c inserido em 150
t inserido em 68
t inserido em 204
t inserido em 216
g inserido em 77
g inserido em 20
c inserido em 322
a inserido em 303
t inserido em 279
t inserido em 205
g inserido em 144
g inserido em 194
g inserido em 123
t inserido em 115
c inserido em 47
g inserido em 59
c inserido em 333
c inserido em 329
c inserido em 23
c inserido em 147
g inserido em 250
g inserido em 178
g inserido em 52
g inserido em 177
g inserido em 235
a inserido em 200
a inserido em 169
c inserido em 64
c inserido em 241
t removido de 24
c inserido em 355
g inserido em 285
a inserido em 59
t inserido em 142
sequencia t a a t g g g c t c c g g c t t c c c c g g g c t c c g c c g a t g a c a a g a g t c c c g c c c a t g a t t t t a a a c g g c c t a a c a c g t t t t t g c c a g a g t a g c c g g a t g t a c g a g c g c c t g c c a g g c t g c g c a a t t g c c t a g a c g g g g a g a g g a t g t t a t c c c c g c g c g a c c t t a g c a c c t a a a g c a t g a g g a a g g t g g a t t t g g t a t g t a g c t g t c c a a g t g g t g a c g g c g c a a t g t a t a t a g g a a t t t t t t t g c c c t c g t g g c g t a c c t t g a g c t a g g a t g a t a t g g a t t c g a g t g a g c a g a g t t g c a c g a a t g a c a g a a g g c a g t a c a g t g t c t g t a a c c g c c g g c c g t g a a g c c t t c g c t g a c a c g t g t c a a c
