t inserido em 0
g inserido em 0
a inserido em 2
a inserido em 3
t inserido em 1
a inserido em 0
a inserido em 4
c inserido em 4
g inserido em 6
a inserido em 9
g inserido em 8
a inserido em 9
c inserido em 10
c inserido em 11
a inserido em 8
a inserido em 3
t inserido em 14
a inserido em 1
c inserido em 11
t inserido em 15
c inserido em 18
g inserido em 5
t inserido em 11
c inserido em 9
t inserido em 2
t inserido em 13
t inserido em 19
t inserido em 14
a inserido em 2
t inserido em 19
a inserido em 16
t inserido em 16
c inserido em 2
c inserido em 33
a inserido em 14
a inserido em 24
c inserido em 35
c inserido em 14
c inserido em 2
g inserido em 1
g inserido em 36
t inserido em 30
sufixo a g a t t c t c t c g a a c c -> c c a a g c t c t c t t a g a
a inserido em 31
c inserido em 22
t inserido em 44
t inserido em 41
g inserido em 38
g inserido em 35
c inserido em 4
c inserido em 8
c inserido em 49
g inserido em 8
a inserido em 26
g inserido em 52
t inserido em 22
c inserido em 19
c inserido em 6
a inserido em 39
t inserido em 33
g inserido em 35
g inserido em 11
c inserido em 37
g inserido em 41
g inserido em 26
a inserido em 16
g inserido em 24
t inserido em 24
c inserido em 61
t inserido em 41
a inserido em 27
a inserido em 38
t inserido em 4
g inserido em 55
t inserido em 63
a inserido em 59
a inserido em 63
g inserido em 41
g inserido em 61
t inserido em 12
t inserido em 10
c inserido em 79
a inserido em 2
t inserido em 34
sequencia a g a a c t c c c a t t g c t g g t a g a t c a c g c c t g a a a t t g t t t c a a t a a g t c g t c t c c g a a a a g g c g t a g c t g a c t t t t c a g a c g c t
g inserido em 47
g inserido em 60
a inserido em 72
c inserido em 66
c inserido em 39
g inserido em 28
a inserido em 27
g inserido em 29
g inserido em 0
t inserido em 45
c inserido em 80
c inserido em 84
a inserido em 46
g inserido em 47
a inserido em 85
t inserido em 84
c inserido em 80
t inserido em 96
t inserido em 54
c inserido em 41
a inserido em 90
g inserido em 0
g inserido em 26
t inserido em 31
c inserido em 81
t inserido em 64
c inserido em 46
t inserido em 106
a inserido em 34
t inserido em 68
c inserido em 26
t inserido em 37
c inserido em 4
g inserido em 95
g inserido em 21
a inserido em 110
c inserido em 74
c inserido em 94
t inserido em 78
t inserido em 86
t inserido em 86
subsequencia a a g a t t c g c << 45
a inserido em 108
a inserido em 54
t inserido em 5
t inserido em 108
t inserido em 117
t inserido em 112
t inserido em 121
t inserido em 76
a inserido em 101
c inserido em 92
g inserido em 65
g inserido em 111
g inserido em 120
c inserido em 78
t inserido em 72
a inserido em 34
t inserido em 82
t inserido em 102
g inserido em 118
t inserido em 82
g inserido em 45
g inserido em 81
a inserido em 19
a inserido em 122
g inserido em 39
a inserido em 9
g inserido em 124
t inserido em 88
t inserido em 120
a inserido em 110
a inserido em 18
t inserido em 35
c inserido em 15
t inserido em 81
c inserido em 5
g inserido em 54
g inserido em 100
t inserido em 5
c inserido em 21
a inserido em 148
g inserido em 64
t removido de 39
g inserido em 1
g inserido em 130
g inserido em 45
g inserido em 26
a inserido em 162
t inserido em 89
g inserido em 38
g inserido em 110
g inserido em 157
a inserido em 151
t inserido em 43
a inserido em 47
c inserido em 124
g inserido em 2
g inserido em 158
t inserido em 91
c inserido em 111
c inserido em 20
t inserido em 119
g inserido em 113
c inserido em 15
c inserido em 92
g inserido em 2
g inserido em 45
t inserido em 96
g inserido em 61
a inserido em 38
c inserido em 121
t inserido em 105
c inserido em 88
a inserido em 51
c inserido em 167
a inserido em 186
t inserido em 74
a inserido em 95
a inserido em 65
c inserido em 53
g inserido em 188
a inserido em 201
t inserido em 180
t inserido em 111
subsequencia c a g t a g g t t c a g t c g a t c g c g t g a g t c c g a >> 28
c inserido em 106
g inserido em 98
a inserido em 161
t inserido em 42
t inserido em 71
g inserido em 129
t inserido em 110
t inserido em 117
c inserido em 75
a inserido em 13
c inserido em 181
t inserido em 117
a inserido em 98
a inserido em 142
a inserido em 127
g inserido em 125
a inserido em 105
t inserido em 6
c inserido em 14
a inserido em 165
g inserido em 147
c inserido em 218
g inserido em 144
a inserido em 95
c inserido em 72
c inserido em 127
a inserido em 70
t inserido em 45
g inserido em 157
a inserido em 81
a inserido em 34
g inserido em 91
g inserido em 52
c inserido em 26
t inserido em 9
a inserido em 113
g inserido em 118
g inserido em 24
t inserido em 199
a inserido em 30
t inserido em 156
subsequencia c g g c g g a t c g g t t t c c c g t a c a a t a a c a g t g g a a g c t a c g << 59
t inserido em 117
c inserido em 50
c inserido em 199
g inserido em 150
a inserido em 41
c inserido em 126
c inserido em 62
g inserido em 47
a inserido em 166
g inserido em 92
a inserido em 241
g inserido em 186
c inserido em 26
c inserido em 163
a inserido em 132
g inserido em 6
c inserido em 102
c inserido em 92
a inserido em 96
a inserido em 150
a inserido em 104
t inserido em 207
a inserido em 234
a inserido em 203
c inserido em 216
a inserido em 199
g inserido em 202
g inserido em 93
t inserido em 67
g inserido em 14
a inserido em 167
g inserido em 37
c inserido em 183
t inserido em 279
a inserido em 238
c inserido em 255
g inserido em 267
t inserido em 132
c inserido em 205
t inserido em 41
t inserido em 216
g removido de 151
t inserido em 115
c inserido em 196
t inserido em 114
g inserido em 3
g inserido em 139
c inserido em 270
t inserido em 137
g inserido em 69
t inserido em 259
c inserido em 284
g inserido em 216
t inserido em 176
c inserido em 123
a inserido em 225
g inserido em 174
t inserido em 249
g inserido em 221
a inserido em 168
t inserido em 161
a inserido em 134
t inserido em 97
t inserido em 249
g inserido em 307
g inserido em 111
g inserido em 73
g inserido em 229
t inserido em 215
a inserido em 240
a inserido em 177
c inserido em 112
c inserido em 52
t inserido em 170
c inserido em 218
t inserido em 254
c inserido em 260
c inserido em 192
a inserido em 92
a inserido em 50
a inserido em 172
g inserido em 166
t inserido em 137
sequencia g g g g g g a g t g c t t c t g a a c a c a t c c c c g a c c c c t a t g c g a c t t g a a g a g t a g a c g g a a t c c t t a g c g g g c g g c t t g c a a c a a t g c g g a g t g t a a a g c a g t a t g c g a a g a c t t g t t c g c a c t g g t c t t c g g c c g g a t c t g g t t a t c c c t t t g g t a c a a c t a a a c a g t g g a a g t c t a t a a c g c a a c t a a g a g a g a t a t c c a a a c g a g a g a t c g a t g c c g t t c c t t t c t t a t a g t t c c a t g g g g g a g a t a t t a g a t c t t t t c g t c g t c c c t t t t t a t t a a a a t c t c t c a a c a t g t a g g t c t c a g t c c g a t a c g g c g t c g c a g t c c g a t g t
g inserido em 305
c inserido em 79
g inserido em 74
t inserido em 210
c inserido em 141
t inserido em 193
t inserido em 257
a inserido em 153
c inserido em 78
a inserido em 203
c inserido em 211
g inserido em 230
g inserido em 330
t inserido em 333
t inserido em 219
a inserido em 34
c inserido em 36
a inserido em 103
t inserido em 5
a inserido em 322
g inserido em 95
g inserido em 243
c inserido em 180
g inserido em 186
c inserido em 149
g inserido em 351
c inserido em 110
a inserido em 65
g inserido em 82
c inserido em 29
c inserido em 222
t inserido em 326
g inserido em 96
a inserido em 323
c inserido em 300
g inserido em 82
c inserido em 52
t inserido em 23
t inserido em 271
g inserido em 177
c inserido em 237
g removido de 324
t inserido em 258
a inserido em 212
c inserido em 117
t inserido em 333
c inserido em 101
c inserido em 3
g inserido em 50
a inserido em 301
a inserido em 266
a inserido em 30
c inserido em 90
a inserido em 323
c inserido em 115
c inserido em 318
t inserido em 347
a inserido em 133
t inserido em 113
g inserido em 238
a inserido em 123
a inserido em 178
t inserido em 118
t inserido em 116
c inserido em 132
a inserido em 215
c inserido em 63
g inserido em 354
g inserido em 65
a inserido em 267
c inserido em 311
g inserido em 71
t inserido em 285
a inserido em 151
g inserido em 177
g inserido em 246
g inserido em 248
t inserido em 345
a inserido em 288
g inserido em 360
g inserido em 37
g inserido em 81
c inserido em 244
sequencia g g g c g g t g a g t g c t t c t g a a c a c a t t c c c c a g c a c c c g c t a a c t g c g a c t t g g a a g a c g t a g a c c g g g a a t c g c t a t a g c g g g g c g g c t g t g g c g c c a a c c a a t g c g g g a c g g t g t a a t a g t c c t a a g t a a t c c g c g c a a g a c a t t g t t c g c a a c t g g t c t t c g g c c g g a t c t g c g c t t g a t c c c t t t a a g g t a c a a c g t a a a c a g t g g a a c g t c t a g t a a c a g c a a c t a a g a g a t a g a t a t c a c c a a a g c g g c g a c g a g a t t c c t g a t g c c g t t a c c g t t t c t t g t a t a a a g t t t c c a t g g g g g t a g a t a t t a g a t t c t t c t t c g t c a g t c c c t t t t t a c c t t a a a a a t t c t c t c a a c a t t a g g g t a t g c t c t a t g t c c g g a a t a c g g c g t c g c a g g t t c c g a t g g t
g inserido em 369
t inserido em 316
c inserido em 111
c inserido em 10
sequencia g g g c g g t g a g c t g c t t c t g a a c a c a t t c c c c a g c a c c c g c t a a c t g c g a c t t g g a a g a c g t a g a c c g g g a a t c g c t a t a g c g g g g c g g c t g t g g c g c c a a c c a a t g c g g g a c c g g t g t a a t a g t c c t a a g t a a t c c g c g c a a g a c a t t g t t c g c a a c t g g t c t t c g g c c g g a t c t g c g c t t g a t c c c t t t a a g g t a c a a c g t a a a c a g t g g a a c g t c t a g t a a c a g c a a c t a a g a g a t a g a t a t c a c c a a a g c g g c g a c g a g a t t c c t g a t g c c g t t a c c g t t t c t t g t a t a a a g t t t c c a t g g g g g t a g a t a t t a g a t t t c t t c t t c g t c a g t c c c t t t t t a c c t t a a a a a t t c t c t c a a c a t t a g g g t a t g g c t c t a t g t c c g g a a t a c g g c g t c g c a g g t t c c g a t g g t
