t inserido em 0
sequencia t
c inserido em 1
t inserido em 2
c inserido em 0
t inserido em 1
g inserido em 5
a inserido em 2
g inserido em 5
t inserido em 4
a inserido em 6
a inserido em 6
t inserido em 2
a inserido em 7
g inserido em 13
a inserido em 4
t inserido em 7
c inserido em 6
c inserido em 13
g inserido em 5
c inserido em 5
a inserido em 2
g inserido em 3
g inserido em 4
t inserido em 13
t inserido em 11
a inserido em 17
g inserido em 4
c inserido em 21
g inserido em 13
c inserido em 26
t inserido em 9
a inserido em 3
g inserido em 0
c inserido em 18
c inserido em 26
g inserido em 20
c inserido em 28
t inserido em 7
c inserido em 9
a inserido em 0
a inserido em 4
t inserido em 32
c inserido em 36
a inserido em 2
g inserido em 4
c inserido em 19
sufixo c t g t t c a a a c t c c a c c g c t g g -> g g t c g c c a c c t c a a a c t t g t c
t inserido em 3
c inserido em 23
a inserido em 45
t inserido em 14
c inserido em 45
c inserido em 39
c inserido em 40
c inserido em 27
g inserido em 41
g inserido em 20
a inserido em 5
a inserido em 39
g inserido em 11
a inserido em 12
t inserido em 18
t inserido em 3
a inserido em 60
c inserido em 32
c inserido em 44
c inserido em 59
a inserido em 9
a inserido em 16
c inserido em 56
a inserido em 51
c inserido em 58
t inserido em 42
g inserido em 31
t inserido em 46
g inserido em 20
c inserido em 15
a inserido em 44
g inserido em 18
g inserido em 72
t inserido em 31
a inserido em 53
g inserido em 31
g inserido em 25
g inserido em 42
a inserido em 78
g inserido em 41
t inserido em 63
c inserido em 10
g inserido em 30
g inserido em 22
g inserido em 7
subsequencia t g c t a g a t g g t c c g g t c t g c g g c c g g t a c t g c t c a a c a c << 6
g inserido em 50
g inserido em 3
t inserido em 11
g inserido em 71
a inserido em 19
c inserido em 18
a inserido em 34
g inserido em 91
c inserido em 4
c inserido em 93
a inserido em 33
c inserido em 81
t inserido em 95
a inserido em 77
g inserido em 26
a inserido em 58
a inserido em 57
a inserido em 6
c inserido em 99
g inserido em 110
c inserido em 104
a inserido em 100
a inserido em 13
c inserido em 106
t inserido em 5
g inserido em 21
a inserido em 53
c inserido em 36
t inserido em 33
c inserido em 91
a inserido em 79
c inserido em 1
g inserido em 104
g inserido em 119
c inserido em 8
g inserido em 31
t inserido em 73
t inserido em 26
t inserido em 50
g inserido em 8
c inserido em 5
g inserido em 44
t inserido em 97
c inserido em 55
c inserido em 85
t removido de 28
a inserido em 45
g inserido em 66
c inserido em 100
g inserido em 89
a inserido em 71
a inserido em 103
a inserido em 69
a inserido em 133
a inserido em 7
g inserido em 44
a inserido em 56
a inserido em 8
g inserido em 122
a inserido em 107
t inserido em 35
g inserido em 35
g inserido em 148
g inserido em 9
c inserido em 65
g inserido em 150
t inserido em 10
g inserido em 80
g inserido em 4
t inserido em 109
c inserido em 77
a inserido em 98
g inserido em 7
g inserido em 32
t inserido em 146
g inserido em 29
t inserido em 53
t inserido em 33
g inserido em 109
g inserido em 26
t inserido em 110
g inserido em 123
c inserido em 38
a inserido em 81
g inserido em 152
a inserido em 25
a inserido em 76
g inserido em 73
a inserido em 92
a inserido em 83
a inserido em 108
g removido de 65
c inserido em 36
a inserido em 40
c inserido em 142
g inserido em 154
t inserido em 15
c inserido em 148
a inserido em 85
t inserido em 141
c inserido em 159
t inserido em 179
c inserido em 72
c inserido em 59
t inserido em 20
a inserido em 125
t inserido em 184
g inserido em 170
t inserido em 33
t inserido em 191
g inserido em 46
a inserido em 4
g inserido em 185
a inserido em 149
g inserido em 199
g inserido em 18
t inserido em 91
c inserido em 168
c inserido em 68
t inserido em 57
t inserido em 86
a inserido em 17
c inserido em 158
a inserido em 113
g inserido em 17
c inserido em 97
c inserido em 9
g inserido em 120
t inserido em 91
a inserido em 188
a inserido em 155
c inserido em 82
c inserido em 108
g inserido em 91
t inserido em 218
c inserido em 149
a inserido em 9
subsequencia c c c g c c c c a c c g a c g c a c g t c c a g g g c a t g t c a c a g c t t t a g g a t g g t << 123
c inserido em 188
t inserido em 218
c inserido em 44
c inserido em 77
c inserido em 214
a inserido em 44
t inserido em 85
g inserido em 17
c inserido em 66
a inserido em 12
g inserido em 155
g inserido em 80
a inserido em 134
t inserido em 4
t inserido em 154
g inserido em 209
g inserido em 91
g inserido em 128
c inserido em 37
c inserido em 114
a inserido em 85
a inserido em 16
a inserido em 140
c inserido em 154
g inserido em 187
g inserido em 199
a inserido em 76
g inserido em 23
g inserido em 238
c inserido em 86
a inserido em 197
a inserido em 112
a inserido em 115
a inserido em 195
t inserido em 154
c inserido em 39
g inserido em 41
t inserido em 79
g inserido em 174
t inserido em 186
t inserido em 187
a inserido em 24
t inserido em 80
t inserido em 187
a inserido em 94
a removido de 45
a inserido em 10
t inserido em 14
a inserido em 229
a inserido em 232
a inserido em 220
t inserido em 97
a inserido em 136
t inserido em 199
t inserido em 37
g inserido em 265
g inserido em 228
c inserido em 15
g inserido em 28
c inserido em 58
t inserido em 96
c inserido em 142
g inserido em 175
c inserido em 111
g inserido em 78
t inserido em 51
c inserido em 195
a inserido em 47
c inserido em 53
t inserido em 108
c inserido em 273
a inserido em 81
t inserido em 160
a inserido em 257
a inserido em 278
g inserido em 36
a inserido em 17
c inserido em 1
a inserido em 242
g inserido em 105
g inserido em 154
a inserido em 135
t inserido em 249
c inserido em 152
t inserido em 68
t inserido em 54
g inserido em 5
g inserido em 74
t inserido em 243
a inserido em 191
g inserido em 275
prefixo a c c g a g t a g g c g a a c c t c a a a a a g t t g t t g a g g a g g c a t g t c a t g g t a a c c a g t g t c t c a -> a c t c t g t g a c c a a t g g t a c t g t a c g g a g g a g t t g t t g a a a a a c t c c a a g c g g a t g a g c c a
t inserido em 158
t inserido em 250
t inserido em 3
c inserido em 8
g inserido em 68
a inserido em 294
t inserido em 30
c inserido em 2
g inserido em 117
g inserido em 180
t inserido em 254
a inserido em 10
a inserido em 179
a inserido em 179
t inserido em 150
g inserido em 101
c inserido em 212
g inserido em 197
g inserido em 150
g inserido em 167
a inserido em 237
a inserido em 274
c inserido em 114
a inserido em 244
g inserido em 329
g inserido em 170
g inserido em 161
t inserido em 53
g inserido em 1
t inserido em 156
t inserido em 136
t inserido em 247
t inserido em 208
c inserido em 267
a inserido em 168
c inserido em 20
t inserido em 75
t inserido em 161
t inserido em 147
a inserido em 69
g inserido em 103
c inserido em 103
c inserido em 345
a inserido em 191
g inserido em 26
prefixo a g c c t t c t g t c a g a c c a a t g c g t a c t g g t a c g g a g t g a g t t g t t g a a a a a c t c c a a t g c -> c g t a a c c t c a a a a a g t t g t t g a g t g a g g c a t g g t c a t g c g t a a c c a g a c t g t c t t c c g a
g inserido em 320
c inserido em 26
c inserido em 83
c inserido em 74
a inserido em 250
g inserido em 159
g inserido em 220
a inserido em 279
t inserido em 209
g inserido em 149
t inserido em 184
g inserido em 184
c inserido em 42
a inserido em 103
t inserido em 217
g inserido em 181
g inserido em 185
t inserido em 155
g inserido em 166
c inserido em 60
t inserido em 316
g inserido em 66
t inserido em 64
t inserido em 37
c inserido em 5
a inserido em 104
g inserido em 201
c inserido em 327
c inserido em 98
t inserido em 21
t inserido em 76
a inserido em 104
c inserido em 354
c inserido em 34
c inserido em 188
g inserido em 226
g inserido em 103
t inserido em 344
t inserido em 162
c inserido em 26
g inserido em 244
c inserido em 397
g inserido em 83
g inserido em 204
a inserido em 128
g removido de 98
c inserido em 136
t inserido em 71
g inserido em 328
g inserido em 92
c inserido em 100
a inserido em 315
a inserido em 284
g inserido em 56
c inserido em 366
t inserido em 98
c inserido em 248
g inserido em 59
g inserido em 150
g inserido em 396
t inserido em 126
c inserido em 209
a inserido em 381
a inserido em 94
c inserido em 326
a inserido em 60
c inserido em 83
a inserido em 407
c inserido em 245
a inserido em 130
g inserido em 414
g inserido em 323
t inserido em 379
g inserido em 26
t inserido em 315
c inserido em 311
t inserido em 395
c inserido em 191
t inserido em 174
c inserido em 237
t inserido em 89
a inserido em 54
c inserido em 247
a inserido em 329
c inserido em 51
c inserido em 68
a inserido em 337
g inserido em 205
c inserido em 296
g inserido em 43
t inserido em 196
sequencia c g t a a c c c t c a a a a a g t t g t t t g a g t g c g a c g g c a t c g g t c a t g t g c g t c a a c c c a a g a c g t g g a t c t t c c c g c a g g t a t t g g a g c c t c a t a g t g a c a g a g t a g c c t c t c t g c c g c c c c g g c a c c c a a c c g a a a g t a c c c g g c a a g c g t t a t c c c a g g g c g g t g c c g c a a t a t t g t c a t t g t c c t a g g c t t t t t a g t g c a g t g g a g a g g t t t a t a c c a g a c g g c c g a g g a g g t t g c g g g g t a c g c t g t a g t c c t a c g g c a a t c g t t g t c c g g a a g a a a t g g a t g t c t t c a a c c g c g c c c t g g t c t a g g t a c g t a c t c g a a c t a c a t t t t a g a c g t a c g c g a a a c g a a g c g a a c a g t a a t g t a c g a t g g t a a a g t t t a g c c t c a a a a c t c a c a t a a g t c g g c g g g c a a c t t g g t g t c a g t a c g a a c g g c a a g t t a g c a g t t c a t g c c g
t inserido em 219
g inserido em 155
t inserido em 365
g inserido em 31
c inserido em 108
a inserido em 374
a inserido em 222
sequencia c g t a a c c c t c a a a a a g t t g t t t g a g t g c g a c g g g c a t c g g t c a t g t g c g t c a a c c c a a g a c g t g g a t c t t c c c g c a g g t a t t g g a g c c t c a t a g t g a c a g a g t a g c c t c c t c t g c c g c c c c g g c a c c c a a c c g a a a g t a c c c g g c a a g c g t t a t c c c g a g g g c g g t g c c g c a a t a t t g t c a t t g t c c t a g g c t t t t t a g t g c a g t g g a g a g g t t t a t a c c a g a t a c g g c c g a g g a g g t t g c g g g g t a c g c t g t a g t c c t a c g g c a a t c g t t g t c c g g a a g a a a t g g a t g t c t t c a a c c g c g c c c t g g t c t a g g t a c g t a c t c g a a c t a c a t t t t a g a c g t a c g c g a a a c g a a g c g a a c a g t a a t g t a c t g a t g g t a a a a g t t t a g c c t c a a a a c t c a c a t a a g t c g g c g g g c a a c t t g g t g t c a g t a c g a a c g g c a a g t t a g c a g t t c a t g c c g
