a inserido em 0
g inserido em 1
g inserido em 0
a inserido em 1
c inserido em 0
t inserido em 4
t inserido em 6
c inserido em 0
a inserido em 6
g inserido em 8
t inserido em 1
c inserido em 5
t inserido em 1
g inserido em 0
t inserido em 11
c inserido em 4
a inserido em 11
c inserido em 3
c inserido em 12
g inserido em 7
t inserido em 9
g inserido em 12
a inserido em 22
t inserido em 11
c inserido em 22
t inserido em 16
a inserido em 25
a inserido em 26
c inserido em 13
c inserido em 13
t inserido em 21
c inserido em 5
g inserido em 29
t inserido em 17
g inserido em 20
t inserido em 7
g inserido em 10
t inserido em 31
c inserido em 17
g inserido em 26
c inserido em 28
g inserido em 37
a inserido em 2
c inserido em 37
c inserido em 24
c inserido em 11
t inserido em 8
g inserido em 27
g inserido em 12
sequencia g c a t c t c c t t c g g c g g t a t c c c c g t a t c g g t c g a c t a t g g t c c t g g a a a
c inserido em 24
c inserido em 50
a inserido em 33
g inserido em 36
t inserido em 35
g inserido em 46
c inserido em 6
t inserido em 8
a inserido em 55
g inserido em 7
t inserido em 9
t inserido em 38
g inserido em 21
a inserido em 41
a inserido em 9
t inserido em 40
c inserido em 21
c inserido em 27
g inserido em 56
g inserido em 45
a inserido em 59
t inserido em 17
g inserido em 27
c inserido em 70
c inserido em 16
a inserido em 64
t inserido em 55
g inserido em 62
g inserido em 61
g inserido em 72
c inserido em 77
g inserido em 69
a inserido em 23
t inserido em 75
c inserido em 51
g inserido em 51
a inserido em 33
t inserido em 79
a inserido em 71
a inserido em 81
g inserido em 10
c inserido em 35
a inserido em 45
c inserido em 22
a inserido em 64
t inserido em 84
t inserido em 77
a inserido em 38
sufixo t a c g t g g g t t t a a a a c c a c -> c a c c a a a a t t t g g g t g c a t
a inserido em 37
t inserido em 25
c inserido em 28
t inserido em 41
t inserido em 81
g inserido em 24
a inserido em 39
a inserido em 31
t inserido em 81
g inserido em 36
c inserido em 42
c inserido em 64
g inserido em 89
a inserido em 102
c inserido em 21
t inserido em 89
a inserido em 16
t inserido em 80
a inserido em 15
a inserido em 103
t inserido em 72
c inserido em 88
a inserido em 27
c inserido em 117
g inserido em 108
a inserido em 109
g inserido em 112
a inserido em 1
g inserido em 76
a inserido em 69
t inserido em 34
g inserido em 25
t inserido em 65
g inserido em 15
a inserido em 108
g inserido em 113
a inserido em 105
t inserido em 73
c inserido em 29
t inserido em 91
g inserido em 8
g inserido em 36
t inserido em 76
g inserido em 15
g inserido em 109
c inserido em 60
t inserido em 33
c inserido em 101
sequencia g a c a t c t c g g c a g t t g c g t a t a c c g t g c g c c c g t a g g t g a c t c t a g a t g g c c c a a c c a c t a c c g c t a t c g a g t t c a t t g t t a c g a g c t t g a g c t t a a t t t g c g t g g c g t c a g g t t g a a c a a c c a a g a a a g a t t g t a g g g t g c c a t
g inserido em 31
a inserido em 29
c inserido em 114
a inserido em 137
t inserido em 64
t inserido em 25
a inserido em 4
c inserido em 58
t inserido em 112
t inserido em 13
a inserido em 35
t inserido em 79
g inserido em 112
a inserido em 97
t inserido em 129
c inserido em 156
c inserido em 26
t inserido em 50
c inserido em 51
t inserido em 3
a inserido em 135
c inserido em 144
g inserido em 77
c inserido em 168
c inserido em 29
c inserido em 38
t inserido em 163
t inserido em 125
t inserido em 150
a inserido em 159
c inserido em 173
t inserido em 161
a inserido em 34
g inserido em 146
c inserido em 50
g inserido em 109
a inserido em 120
a inserido em 97
t inserido em 25
a inserido em 133
a inserido em 36
g inserido em 168
c inserido em 45
t inserido em 33
t inserido em 25
g inserido em 31
c inserido em 10
g inserido em 190
prefixo g a c t a a t c t c c g g c a t g t t g c g t a t a t t c c c g g c t t t g c a a g a c c c a g c c g t a g -> g a t g c c g a c c c a g a a c g t t t c g g c c c t t a t a t g c g t t g t a c g g c c t c t a a t c a g
g inserido em 172
c inserido em 134
c inserido em 131
t inserido em 93
t inserido em 176
t inserido em 27
c inserido em 102
c inserido em 166
a inserido em 6
g inserido em 37
a inserido em 198
c inserido em 124
t inserido em 139
t inserido em 5
c inserido em 177
g inserido em 114
a inserido em 7
c inserido em 148
t inserido em 153
t inserido em 28
t inserido em 9
a inserido em 152
g inserido em 178
a inserido em 148
t inserido em 135
g inserido em 184
t inserido em 72
g inserido em 171
a inserido em 52
g inserido em 183
a inserido em 121
c inserido em 107
g inserido em 118
c inserido em 126
t inserido em 78
c inserido em 124
c inserido em 147
c inserido em 175
c inserido em 146
c inserido em 192
a inserido em 136
t inserido em 185
g inserido em 5
a inserido em 173
g inserido em 236
c inserido em 32
a inserido em 131
g inserido em 125
a removido de 8
t inserido em 91
g inserido em 189
a inserido em 1
t inserido em 1
g inserido em 212
t inserido em 123
a inserido em 124
t inserido em 189
t inserido em 175
t inserido em 63
c inserido em 222
a inserido em 239
a inserido em 55
c inserido em 119
g inserido em 191
t inserido em 133
t inserido em 15
a inserido em 54
a inserido em 65
a inserido em 253
g inserido em 164
a inserido em 245
g inserido em 28
a inserido em 110
t inserido em 205
g inserido em 35
t inserido em 205
t inserido em 97
c inserido em 128
g inserido em 87
c inserido em 16
g inserido em 28
g inserido em 128
g inserido em 8
a inserido em 93
g inserido em 245
c inserido em 212
t inserido em 199
g inserido em 166
a inserido em 32
a inserido em 112
g inserido em 166
c inserido em 74
t inserido em 159
g inserido em 22
a inserido em 91
c inserido em 169
g inserido em 44
sufixo a a g c a g t t g t g g a a t t a g g a g t a t g c c c a a a c g t g c -> c g t g c a a a c c c g t a t g a g g a t t a a g g t g t t g a c g a a
c inserido em 257
g inserido em 147
a inserido em 17
c inserido em 81
c inserido em 60
t inserido em 246
a inserido em 224
g inserido em 67
g inserido em 90
a inserido em 239
a inserido em 275
a inserido em 286
a inserido em 58
a inserido em 135
a inserido em 158
g inserido em 31
c inserido em 290
a inserido em 103
a inserido em 163
g inserido em 189
c inserido em 106
c inserido em 33
a inserido em 55
c inserido em 32
g inserido em 12
c inserido em 49
a inserido em 149
g inserido em 155
c inserido em 16
c inserido em 97
c inserido em 217
a inserido em 193
g inserido em 234
g inserido em 148
a inserido em 39
t inserido em 194
t inserido em 47
c inserido em 227
c inserido em 97
c inserido em 223
c inserido em 137
g inserido em 65
c inserido em 204
t inserido em 82
a inserido em 182
t inserido em 178
c inserido em 330
t inserido em 84
sufixo c a t g g t t a c a g c g c g t a t t g c t t g t a g a t a a c a a c g c a c g t g c a c g g t a g c c g t g c c a a a c c c g t a a t g a g g a t t a c a a g g t g t t g a c c g a a -> a a g c c a g t t g t g g a a c a t t a g g a g t a a t g c c c a a a c c g t g c c g a t g g c a c g t g c a c g c a a c a a t a g a t g t t c g t t a t g c g c g a c a t t g g t a c
t inserido em 285
g inserido em 160
a inserido em 31
g inserido em 33
t inserido em 254
t inserido em 18
a inserido em 337
c inserido em 327
g inserido em 107
g inserido em 329
a inserido em 149
a inserido em 336
t inserido em 139
g inserido em 75
a inserido em 313
g inserido em 173
g inserido em 140
c inserido em 61
g inserido em 34
c inserido em 264
g inserido em 141
g inserido em 143
t inserido em 133
g inserido em 262
g inserido em 302
t inserido em 28
c inserido em 102
a inserido em 312
c inserido em 14
t inserido em 75
a inserido em 188
g inserido em 311
a inserido em 82
t inserido em 208
t inserido em 277
t inserido em 70
g inserido em 300
t inserido em 73
c inserido em 134
c inserido em 286
c inserido em 284
c inserido em 91
t inserido em 329
c inserido em 231
t inserido em 338
t inserido em 130
g inserido em 165
c inserido em 339
sufixo g a g t a a t g g c c c a a a c c g t g g c t c g g a t g a g c t a c g t g c c a t c g c a a a c a a t a g a t g t t c g t t a t c g g c g c g a a c a t t a g g t a c -> c a t g g a t t a c a a g c g c g g c t a t t g c t t g t a g a t a a c a a a c g c t a c c g t g c a t c g a g t a g g c t c g g t g c c a a a c c c g g t a a t g a g
t inserido em 189
t inserido em 144
g inserido em 212
g inserido em 58
a inserido em 9
g inserido em 177
c inserido em 47
g inserido em 178
g inserido em 216
t inserido em 328
c inserido em 368
a inserido em 304
t inserido em 35
g inserido em 381
g inserido em 381
t inserido em 352
g inserido em 135
c inserido em 267
t inserido em 398
c inserido em 280
t inserido em 382
g inserido em 30
t inserido em 400
a inserido em 226
g inserido em 170
a inserido em 305
a inserido em 186
g inserido em 347
c inserido em 1
t inserido em 301
a inserido em 58
t inserido em 386
t inserido em 135
a inserido em 261
t inserido em 262
c inserido em 400
t inserido em 94
t inserido em 228
g inserido em 286
g inserido em 266
c inserido em 333
g inserido em 366
c inserido em 417
a inserido em 361
c inserido em 120
g inserido em 97
g inserido em 404
t inserido em 249
prefixo g c t a a t g c g g a t c a g t c g a c c t t a c c c a g g a g t a c g t t a t g g t g c g c c g a c a g g c c t c a t g c t t g c g t a t a c t g c a g t g t t g t g t a t a c g c a g g t a c g c g c a a t t c t t a a t a c t c a g c g c t c g c c a c c g t g c t c t t a a t g a -> a g t a a t t c t c g t g c c a c c g c t c g c g a c t c a t a a t t c t t a a c g c g c a t g g a c g c a t a t g t g t t g t g a c g t c a t a t g c g t t c g t a c t c c g g a c a g c c g c g t g g t a t t g c a t g a g g a c c c a t t c c a g c t g a c t a g g c g t a a t c g
g inserido em 73
c inserido em 185
g inserido em 407
a inserido em 409
a inserido em 360
g inserido em 21
c inserido em 145
a inserido em 425
g inserido em 163
g inserido em 377
g inserido em 144
a inserido em 107
c inserido em 365
a inserido em 264
t inserido em 194
c inserido em 100
t inserido em 69
g inserido em 57
a inserido em 125
c inserido em 116
g inserido em 254
a inserido em 307
g inserido em 168
t inserido em 119
t inserido em 226
g inserido em 234
g inserido em 375
g inserido em 54
g inserido em 427
c inserido em 136
a inserido em 105
t inserido em 56
t inserido em 68
a inserido em 40
c inserido em 174
t inserido em 326
t inserido em 402
g inserido em 121
c inserido em 308
g inserido em 9
c inserido em 76
t inserido em 29
a inserido em 438
c inserido em 451
t inserido em 451
a inserido em 207
a inserido em 308
t inserido em 271
prefixo a g t a a t t c t g c g t g c c a c c g c t g c g c g a c t t c a t a a t t c t t a a a c g c g c a t g g a c g c g a t t a g t g t g t t g t t g a c g t c t c a t a g t g c g t t c g t a c t c c g g a c a g c c g c g c t a g g t a t t a g c a t g g -> g g t a c g a t t a t g g a t c g c g c c g a c a g g c c t c a t g c t t g c g t g a t a c t c t g c a g t t g t t g t g t g a t t a g c g c a g g t a c g c g c a a a t t c t t a a t a c t t c a g c g c g t c g c c a c c g t g c g t c t t a a t g a
a inserido em 106
sequencia g g t a c g a t t a t g g a t c g c g c c g a c a g g c c t c a t g c t t g c g t g a t a c t c t g c a g t t g t t g t g t g a t t a g c g c a g g t a c g c g c a a a t t c t t a a t a c t t c a g c g c g t c g a c c a c c g t g c g t c t t a a t g a c a g t g a c c c a t a t c c a g c t c g a c t a g g c g t a a t c g t g g c g a t t c c a g g c c c t t c a g c a g t c c a t g c g g t t a c a t c g c g g c g a a t c a a t t c g g t g a a a t g g c t a g t c g c t c g g a t c t a t g a t g t g a g t a t a g g a g t g a t c a t c a g a g t c a g t c t a t t g g a t c a c a a g c c g g c g t a t t g a t a t c t g a c t a g c c c c g t c c g t g c a a c g g c c t t a t t a a g g c c a g t c t t t t g t c a g g c a a c a a t t a g c a t g c g a t t a c a a g c g c g g c t t a g t t g c a c t t g g t a a g a t a g t g a c a a a c t g c t a c c g t g c a t c g a g t a c g g t a c t g c g g g g a t t g t c c g c g c a a a c a c c g g c t a t a t t g a g
