a inserido em 0
t inserido em 0
t inserido em 1
c inserido em 3
a inserido em 4
g inserido em 0
g inserido em 1
a inserido em 2
a inserido em 4
g inserido em 2
t inserido em 2
t inserido em 3
a inserido em 6
t inserido em 2
t inserido em 9
a inserido em 10
t inserido em 12
t inserido em 0
c inserido em 5
g inserido em 0
c inserido em 5
t inserido em 14
g inserido em 17
c inserido em 12
g inserido em 16
c inserido em 19
c inserido em 10
g inserido em 8
g inserido em 1
c inserido em 22
t inserido em 3
a inserido em 7
a inserido em 11
c inserido em 26
t inserido em 0
a inserido em 13
c inserido em 7
c inserido em 3
g inserido em 8
a inserido em 7
sufixo a c t t t g a a c c c g t t a c a -> a c a t t g c c c a a g t t t c a
t inserido em 7
a inserido em 31
t inserido em 27
c inserido em 21
a inserido em 10
t inserido em 24
c inserido em 28
a inserido em 2
c inserido em 44
t inserido em 17
t inserido em 31
t inserido em 4
a inserido em 32
t inserido em 18
t inserido em 46
c inserido em 10
g inserido em 29
t inserido em 35
c inserido em 34
a inserido em 10
t inserido em 41
a inserido em 7
t inserido em 10
t inserido em 32
t inserido em 2
c inserido em 44
g inserido em 57
a inserido em 38
t inserido em 29
c inserido em 11
g inserido em 44
c inserido em 39
t inserido em 33
g inserido em 37
c inserido em 46
c inserido em 21
c inserido em 35
c inserido em 21
a inserido em 76
subsequencia a a a c c c g t a << 6
a inserido em 61
g inserido em 67
g inserido em 20
g inserido em 72
c inserido em 75
a inserido em 29
g inserido em 83
t inserido em 61
c inserido em 27
g inserido em 87
t inserido em 14
a inserido em 81
t inserido em 40
g inserido em 79
c inserido em 74
t inserido em 69
a inserido em 65
g inserido em 7
a inserido em 62
t inserido em 17
g inserido em 75
g inserido em 7
a inserido em 82
g inserido em 31
t inserido em 59
t inserido em 75
t inserido em 28
a inserido em 23
g inserido em 89
c inserido em 14
g inserido em 84
c inserido em 15
a inserido em 75
g inserido em 28
a inserido em 20
a inserido em 44
t inserido em 23
a inserido em 81
t inserido em 29
sequencia t g t a g t c g g t a t g c c c t t t a a t c t a g a a g t g g c c c t t a c g c t t a t c a a a t g t t t c c g a a a c c c g t a t g t g t c c t c a c t a t a a a t t a t t t g g c g a c g c a c g a g g t g a c g a t c t t a g c g a
g inserido em 96
a inserido em 18
a inserido em 49
c inserido em 47
g inserido em 72
t inserido em 101
t inserido em 117
c inserido em 122
t inserido em 6
t inserido em 59
c inserido em 126
t inserido em 71
g inserido em 16
c inserido em 27
t inserido em 14
g inserido em 111
g inserido em 23
a inserido em 37
t inserido em 136
g inserido em 130
a inserido em 11
t inserido em 47
t inserido em 125
a inserido em 131
t inserido em 26
g inserido em 10
t inserido em 37
g inserido em 27
t inserido em 80
c inserido em 55
a inserido em 121
t inserido em 99
g inserido em 130
t inserido em 52
a inserido em 14
c inserido em 140
a inserido em 137
a inserido em 76
a inserido em 154
subsequencia t a a a t g t c c g c t t a t g a g t a t c t c a g a a t g t g a g c c c t t a c t t g c t c t a t c c a a a a t g t t >> 49
g inserido em 14
a inserido em 57
g inserido em 124
c inserido em 25
a inserido em 132
a inserido em 82
t inserido em 149
c inserido em 131
c inserido em 110
c inserido em 60
c inserido em 16
t inserido em 131
t inserido em 134
g inserido em 89
g inserido em 151
c inserido em 95
t inserido em 89
c inserido em 173
c inserido em 147
c inserido em 167
a inserido em 81
t inserido em 173
g inserido em 61
g inserido em 29
t inserido em 29
a inserido em 10
t inserido em 63
a inserido em 148
a inserido em 59
g inserido em 64
g inserido em 183
c inserido em 113
a inserido em 95
g inserido em 45
t inserido em 10
c inserido em 8
a inserido em 193
c inserido em 9
t inserido em 74
sequencia t g t a g t t c c c g g t a g t c t g c c g a a a a c c c g c t t t g a t t g t g g t c c t c a g c t a t t a a a t t a t t t a g g c a g t g g c a t c g t a a a t g t c c g c t t a t g a a g t a a t a c t t g c a g a a c t g t g a g c c c c t t a c t t g c t c c t a t c c a a a a t g t t g t g c t a c t a c g g a a a g g t c g g a c g t g a a t c c t t t a t a g c g c c c t g g a a c t a
g inserido em 121
a inserido em 194
c inserido em 120
t inserido em 103
c inserido em 197
c inserido em 10
t inserido em 83
t inserido em 136
g inserido em 8
g inserido em 104
c inserido em 111
g inserido em 101
t inserido em 25
c inserido em 129
t inserido em 163
g inserido em 151
g inserido em 162
a inserido em 203
g inserido em 117
g inserido em 152
g inserido em 145
g inserido em 191
a inserido em 182
a inserido em 95
t inserido em 13
c inserido em 46
t inserido em 201
t inserido em 167
a inserido em 186
a inserido em 18
g inserido em 22
c inserido em 163
g inserido em 214
c inserido em 198
t inserido em 42
a inserido em 140
a inserido em 110
a inserido em 66
a inserido em 60
sufixo t a c g g a a a g g t c a a g g a c g t g c a a g t c c t t t t a t a g c g g c c c a t g g a a a c c t a -> a t c c a a a g g t a c c c g g c g a t a t t t t c c t g a a c g t g c a g g a a c t g g a a a g g c a t
t inserido em 68
g inserido em 92
a inserido em 0
g inserido em 124
a inserido em 18
c inserido em 71
c inserido em 32
t inserido em 61
t inserido em 243
g inserido em 43
c inserido em 161
a inserido em 201
c inserido em 30
g inserido em 32
t inserido em 144
a inserido em 233
a inserido em 229
g inserido em 199
t inserido em 208
t inserido em 35
g inserido em 127
g inserido em 223
g inserido em 206
g inserido em 0
a inserido em 1
c inserido em 96
c inserido em 147
sequencia g a a t g t a g t t c g c c c g t g t a a g a t c t g g c c g a c t g a c t a a c c c g c t t t g g a t t t g t g g c t c c t c a g c t t a a t t a a a t a t c t a t t t a g g c a g t g g c a c t c g t a a a g t t g t c c g c t t a a t g a a g t a g a a t a g g c t t t g g c c a g a g a c t g c t g t a g c c c c c c g t a t a c t t g c t c c t c g t a t c c a a g g a a t c g t t g t g t c g t a t c a t c c g a a a g g g a t a t c c c g g c g a t a t t g t t c c t g a a c g a t g c a a g g a a c t g g a a a g g c a t t
