c inserido em 0
g inserido em 0
t inserido em 1
g inserido em 0
a inserido em 3
t inserido em 4
g inserido em 4
t inserido em 1
t inserido em 7
t inserido em 7
t inserido em 6
c inserido em 8
g inserido em 10
a inserido em 9
a inserido em 13
c inserido em 13
g inserido em 1
a inserido em 14
c inserido em 13
g inserido em 10
c inserido em 20
c inserido em 8
a inserido em 3
g inserido em 9
t inserido em 17
a inserido em 0
g inserido em 1
t inserido em 5
a inserido em 14
g inserido em 19
c inserido em 28
g inserido em 6
a inserido em 31
a inserido em 30
c inserido em 9
c inserido em 25
g inserido em 28
c inserido em 22
t inserido em 35
t inserido em 24
g inserido em 34
c inserido em 9
t inserido em 21
a inserido em 23
t inserido em 36
a inserido em 27
c inserido em 7
c inserido em 34
t inserido em 30
a inserido em 20
prefixo a g g -> g g a
a inserido em 7
a inserido em 37
g inserido em 35
c inserido em 45
c inserido em 46
t inserido em 31
a inserido em 34
a inserido em 29
g inserido em 37
g inserido em 6
a inserido em 3
a inserido em 60
a inserido em 46
t inserido em 18
a inserido em 36
g inserido em 49
t inserido em 0
a inserido em 21
g inserido em 36
c inserido em 65
t inserido em 32
a inserido em 14
c inserido em 48
a inserido em 65
t inserido em 45
t inserido em 21
a inserido em 5
t inserido em 5
a inserido em 65
t inserido em 74
a inserido em 49
a inserido em 15
t inserido em 52
c inserido em 65
a inserido em 12
g inserido em 3
a inserido em 62
a inserido em 77
t inserido em 70
g inserido em 58
a inserido em 8
t inserido em 81
a inserido em 32
t inserido em 36
c inserido em 34
t inserido em 32
t inserido em 75
g inserido em 53
c inserido em 63
sequencia t g g g a a t a a g t t g g a a c a a g a c c t a g t t t a g c t a a c t a t c g t a a t g c a t g a t a g t t a t a g t g t c c g g c c a a c a g t g c t a t c t a c c a g a t a c a t t c c a a c
g inserido em 4
c inserido em 75
a inserido em 28
t inserido em 77
c inserido em 49
g inserido em 82
a inserido em 78
a inserido em 96
a inserido em 18
t inserido em 21
g inserido em 102
g inserido em 82
a inserido em 19
a inserido em 88
c inserido em 34
a inserido em 82
a inserido em 46
c inserido em 99
t inserido em 63
t inserido em 46
a inserido em 106
c inserido em 44
a inserido em 114
a inserido em 77
t inserido em 28
c inserido em 92
c inserido em 61
c inserido em 3
c inserido em 79
g inserido em 128
a inserido em 122
t inserido em 41
t inserido em 94
a inserido em 96
g inserido em 85
a inserido em 93
g inserido em 8
a inserido em 42
g inserido em 83
a inserido em 6
t inserido em 29
t inserido em 1
c inserido em 94
g inserido em 34
a inserido em 129
g inserido em 46
a inserido em 20
t inserido em 65
c inserido em 131
prefixo t t g g c g g a a a g t a a g t t g g a a a c a a a a t g a c t c t t g a g t a -> a t g a g t t c t c a g t a a a a c a a a g g t t g a a t g a a a g g c g g t t
c inserido em 26
t inserido em 117
t inserido em 150
g inserido em 61
t inserido em 68
g inserido em 149
c inserido em 34
g inserido em 142
a inserido em 50
a inserido em 31
t inserido em 118
t inserido em 15
t inserido em 75
c inserido em 20
c inserido em 162
g inserido em 151
t inserido em 32
t inserido em 2
a inserido em 91
a inserido em 90
c inserido em 41
t inserido em 16
t inserido em 18
g inserido em 117
g inserido em 60
a inserido em 133
c inserido em 78
t inserido em 36
c inserido em 75
t inserido em 3
g inserido em 145
a inserido em 87
g inserido em 109
t inserido em 22
t inserido em 62
a inserido em 106
g inserido em 158
a inserido em 123
t inserido em 148
a inserido em 185
a inserido em 186
a inserido em 187
g inserido em 51
t inserido em 0
a inserido em 175
a inserido em 180
g inserido em 107
t inserido em 100
t inserido em 28
subsequencia a t c c a g a c g a a << 62
c inserido em 130
g inserido em 29
a inserido em 76
a inserido em 91
c inserido em 100
g inserido em 36
a inserido em 18
c inserido em 15
g inserido em 42
t inserido em 123
t inserido em 188
g inserido em 152
t inserido em 135
c inserido em 138
g inserido em 55
g inserido em 79
a inserido em 202
c inserido em 172
c inserido em 104
g inserido em 81
a inserido em 53
g inserido em 134
c inserido em 176
g inserido em 95
a inserido em 184
g inserido em 164
g inserido em 187
t inserido em 104
g inserido em 42
g inserido em 202
g inserido em 167
t inserido em 11
c inserido em 93
c inserido em 222
g inserido em 115
g inserido em 52
c inserido em 221
c inserido em 186
g inserido em 136
a inserido em 51
a inserido em 91
a inserido em 167
c inserido em 116
c inserido em 9
c inserido em 167
t inserido em 101
c inserido em 186
a inserido em 107
a inserido em 8
subsequencia t c a g c t a a a t t t a a t c a c a t g a g g t t g g c a a g g t t t g a a a a g a c g a c g g c g g g t t t t c a g c t g a t a g t a a c t g a g c a t c a t a g g c c t a t a g t c t a t a g c t t a c a c t c g c g c a t a t g t t a t a a g t a a g t t g g t g c c g c a t c c a t g a c c g c a a g g a g c c g c a a a c g a c g g g a g c a a c a t t a g c t c c c t g a c g a << 13
c inserido em 96
c inserido em 104
t inserido em 224
g inserido em 235
g inserido em 120
g inserido em 76
a inserido em 98
t inserido em 44
t inserido em 236
c inserido em 78
t inserido em 53
a inserido em 206
g inserido em 61
a inserido em 111
a inserido em 200
g inserido em 258
t inserido em 107
c inserido em 91
g inserido em 124
g inserido em 177
t inserido em 149
t inserido em 53
t inserido em 62
c inserido em 85
g inserido em 49
g inserido em 165
c inserido em 134
g inserido em 16
a inserido em 58
c inserido em 68
t inserido em 146
t inserido em 164
c inserido em 169
a inserido em 87
g inserido em 193
t inserido em 158
t inserido em 271
c inserido em 62
a inserido em 59
g inserido em 274
c inserido em 59
c inserido em 125
t inserido em 42
g inserido em 222
g inserido em 93
a inserido em 87
g inserido em 144
g inserido em 212
t inserido em 13
subsequencia c c g a g t g t a a t c a t a a c << 135
a inserido em 259
a inserido em 208
a inserido em 34
c inserido em 298
a inserido em 122
t inserido em 148
a inserido em 147
g inserido em 168
t inserido em 183
c inserido em 166
g inserido em 113
c inserido em 236
c inserido em 64
c inserido em 285
g inserido em 52
c inserido em 286
a inserido em 108
a inserido em 247
t inserido em 106
c inserido em 223
g inserido em 91
t inserido em 243
a inserido em 14
a inserido em 7
c inserido em 15
g inserido em 198
g inserido em 163
c inserido em 34
t inserido em 132
a inserido em 209
a inserido em 77
t inserido em 105
g inserido em 314
c inserido em 203
c inserido em 151
g inserido em 189
c inserido em 151
a inserido em 115
c inserido em 167
t inserido em 140
g inserido em 117
c inserido em 137
c inserido em 95
t inserido em 318
a inserido em 229
c inserido em 170
a inserido em 263
a inserido em 161
t inserido em 157
sufixo t g g t c g g c t c t g c a a t c t c a t a g c a c g c g c a a g g a a g c c c g c a a a c g g g a c g g g a a c t g c a g a c a a t t a g c t c c c t g g a c a g a a t t t g a a g a a t c t c t t g a t t a t g c c c t a c t g a c a g t g g g c a a g t a g a t c c -> c c t a g a t g a a c g g g t g a c a g t c a t c c c g t a t t a g t t c t c t a a g a a g t t t a a g a c a g g t c c c t c g a t t a a c a g a c g t c a a g g g c a g g g c a a a c g c c c g a a g g a a c g c g c a c g a t a c t c t a a c g t c t c g g c t g g t
t inserido em 145
c inserido em 295
c inserido em 288
g inserido em 345
a inserido em 118
g inserido em 9
a inserido em 112
a inserido em 57
a inserido em 55
a inserido em 104
c inserido em 223
g inserido em 191
t inserido em 174
a inserido em 134
t inserido em 268
c inserido em 85
g inserido em 291
t inserido em 124
t inserido em 311
a inserido em 51
c inserido em 292
g inserido em 30
g inserido em 182
c inserido em 344
c inserido em 236
g inserido em 234
a inserido em 348
g inserido em 168
g inserido em 65
c inserido em 339
g inserido em 213
t inserido em 16
a inserido em 318
a inserido em 265
c inserido em 317
a inserido em 159
c inserido em 279
c inserido em 60
t inserido em 331
c inserido em 281
t inserido em 263
a inserido em 320
g inserido em 97
g inserido em 60
a inserido em 125
c inserido em 88
t inserido em 364
t inserido em 274
g inserido em 35
sufixo g g t -> t g g
t inserido em 353
g inserido em 31
c inserido em 318
t inserido em 306
g inserido em 76
g inserido em 32
a inserido em 247
g inserido em 254
t inserido em 64
t inserido em 160
g inserido em 186
c inserido em 193
a inserido em 163
a inserido em 380
c inserido em 87
t inserido em 295
a inserido em 274
g inserido em 79
t inserido em 130
t inserido em 39
a inserido em 287
a inserido em 137
a inserido em 227
t inserido em 40
t inserido em 66
g inserido em 171
a inserido em 173
g inserido em 337
c inserido em 146
g inserido em 222
t inserido em 257
g inserido em 12
a inserido em 193
a inserido em 264
c inserido em 273
t inserido em 316
c inserido em 267
t inserido em 149
g inserido em 132
t inserido em 164
c inserido em 404
a inserido em 32
a inserido em 206
g inserido em 233
c inserido em 51
g inserido em 128
t inserido em 242
a inserido em 254
c inserido em 84
prefixo t t c a g c t a a g a a g t t t t t c a a a t g c a c a t g a g a g g g g t t g g t t g c c a a a g g c t t t g a a a t a a g a t c a g g t t c a a g c g g g g c g t t c g g g a c a c g t t c c t t c a t c g a c c g c t g a t g a g t a a c t c g g a a g a g g c a c g t a g c t t c a a a t a a t g a g t c a t g a c c c t a t a g a g t t c t a c a t a t t c a g a a g c t t t t a c c g a g t g t a a a t g -> g t a a a t g t g a g c c a t t t t c g a a g a c t t a t a c a t c t t g a g a t a t c c c a g t a c t g a g t a a t a a a c t t c g a t g c a c g g a g a a g g c t c a a t g a g t a g t c g c c a g c t a c t t c c t t g c a c a g g g c t t g c g g g g c g a a c t t g g a c t a g a a t a a a g t t t c g g a a a c c g t t g g t t g g g g a g a g t a c a c g t a a a c t t t t t g a a g a a t c g a c t t
t inserido em 54
a inserido em 210
a inserido em 320
a inserido em 373
c inserido em 43
c inserido em 428
a inserido em 407
a inserido em 326
t inserido em 136
c inserido em 222
c inserido em 347
a inserido em 128
t inserido em 202
c inserido em 418
g inserido em 456
g inserido em 75
t inserido em 444
c inserido em 1
a inserido em 458
g inserido em 7
a inserido em 158
g inserido em 420
g inserido em 115
a inserido em 20
g inserido em 3
t inserido em 338
c inserido em 257
a inserido em 434
a inserido em 337
a inserido em 347
c inserido em 416
t inserido em 194
t inserido em 157
g inserido em 343
t inserido em 275
t inserido em 194
t inserido em 455
g inserido em 302
c inserido em 241
c inserido em 347
t inserido em 182
c inserido em 399
a inserido em 417
a inserido em 467
c inserido em 355
g inserido em 109
t inserido em 82
g inserido em 383
sequencia g c t g a a a t g g t g a g c c a t t t t a c g a a g a c t t a t a c a t c t t g a g a t a t c c c c a g t a c t g a t g t a a t a a a c t t c g a t g c a c g g g t a g a a g g c t c a a t g a g t a g t c g c c a g c t g a c t t c c t t g g c a c a g g g c t t g c g g g a g c g a a c t t t g g a c t a g a a t a a a t g t t t a c g g a a a c c g t t g g t t g g g g t a g a g t a c a c g t a t a t a c t t t t t g a a g a a t c t g a c t t c t c g c a a a t a a a c c t t c a c g a a t c c c c c a c g t g c g c g g g c a g t c t a a t g c g t g c g g a t a t g t a a g t t a a g t t t c c t a a g c c a a t g g g a c c a g c g g g t g a c a g t c a a t c c c g t t a t a t a a t g a t t c a t a t c g c t a t a c g a t a c c a g t t t t a a c g a c a g g t c t c g c t c g a t c g t g a a c c a g a c g c t a c c a a a c g g a g c c t a g a g t g c a a a c g c c c c g a t a g a g a g c a c c g c g c a a c c t a g c a a t a c t c t c t a a a c t g t c t c g g c t g t g a g g
