a inserido em 0
sequencia a
t inserido em 0
a inserido em 2
a inserido em 2
c inserido em 4
c inserido em 4
t inserido em 2
g inserido em 7
t inserido em 8
g inserido em 0
c inserido em 1
c inserido em 4
g inserido em 7
g inserido em 0
a inserido em 13
g inserido em 12
c inserido em 3
a inserido em 2
c inserido em 11
g inserido em 9
g inserido em 10
c inserido em 14
g inserido em 18
c inserido em 23
c inserido em 14
t inserido em 9
a inserido em 2
a inserido em 18
t inserido em 24
a inserido em 25
g inserido em 3
c inserido em 18
a inserido em 1
g inserido em 9
t inserido em 24
a inserido em 15
g inserido em 13
c inserido em 0
g inserido em 29
a inserido em 5
g inserido em 7
sufixo a t c g c g g t a g a t c -> c t a g a t g g c g c t a
c inserido em 29
a inserido em 15
a inserido em 20
g inserido em 39
g inserido em 30
a inserido em 2
a inserido em 27
g inserido em 33
a inserido em 46
t inserido em 12
g inserido em 0
t inserido em 6
a inserido em 7
a inserido em 12
c inserido em 22
t inserido em 14
a inserido em 48
t inserido em 11
g inserido em 33
c inserido em 7
a inserido em 4
t inserido em 59
c inserido em 30
a inserido em 16
c inserido em 17
t inserido em 66
a inserido em 46
a inserido em 61
g inserido em 42
c inserido em 35
t inserido em 57
t inserido em 54
t inserido em 0
g inserido em 55
g inserido em 65
a inserido em 47
t inserido em 47
g inserido em 12
c inserido em 32
a inserido em 5
subsequencia a c a g a g g c >> 23
c inserido em 76
c inserido em 16
a inserido em 0
c inserido em 41
t inserido em 4
t inserido em 55
c inserido em 17
a inserido em 81
c inserido em 12
t inserido em 38
t inserido em 80
g inserido em 66
g inserido em 16
a inserido em 65
a inserido em 87
t inserido em 31
t inserido em 9
c inserido em 92
t inserido em 69
c inserido em 27
c inserido em 37
a inserido em 87
c inserido em 3
a inserido em 13
c inserido em 50
c inserido em 54
a inserido em 58
t inserido em 12
t inserido em 38
t inserido em 108
c inserido em 99
t inserido em 87
a inserido em 41
c inserido em 12
a inserido em 107
t inserido em 34
t inserido em 1
g inserido em 25
t inserido em 102
c inserido em 36
prefixo a t t g c c t g a a a t a c t g a t c c a a g g a -> a g g a a c c t a g t c a t a a a g t c c g t t a
t inserido em 103
g inserido em 77
g inserido em 17
a inserido em 101
a inserido em 24
c inserido em 27
a inserido em 49
c inserido em 122
a inserido em 109
c inserido em 110
g inserido em 121
g inserido em 100
t inserido em 64
t inserido em 7
t inserido em 43
t inserido em 4
c inserido em 101
t inserido em 93
g inserido em 47
t inserido em 32
t inserido em 47
t inserido em 113
c inserido em 10
g inserido em 103
g inserido em 35
c inserido em 90
g inserido em 8
g inserido em 10
g inserido em 43
t inserido em 121
c inserido em 2
t inserido em 78
g inserido em 8
a inserido em 149
g inserido em 25
g inserido em 1
g inserido em 85
c inserido em 141
c inserido em 102
sequencia a g g c g a t a c g c g t g t c a g t c a t a a a g g g t c c g t a t a c g c t g g c t g a a g c c a c t t t c t c g t t t t g a a c a c a c t t c g t c c g t a t c c g g c c a t a c a a g g c c t c g t c g t a g a a t t t g t a g g a c c a t g g a g g t t c a g g a g a c t t t c a c c g a a a g a c c c t a c t t a t
